#############################################################################
# Makefile for building: PaymentServer
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Apr 15 10:19:28 2013
# Project:  PaymentServer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile PaymentServer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/libxml2
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)   -lpthread -lxml2 -lcurl 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		threadpool.cpp \
		thread.cpp \
		paymentserver.cpp \
		paypal.cpp \
		md5/md5.c \
		data/param.cpp \
		data/authorise.cpp \
		data/response.cpp \
		rqueue.cpp \
		workerthread.cpp \
		data/redparam.cpp 
OBJECTS       = main.o \
		threadpool.o \
		thread.o \
		paymentserver.o \
		paypal.o \
		md5.o \
		param.o \
		authorise.o \
		response.o \
		rqueue.o \
		workerthread.o \
		redparam.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		PaymentServer.pro
QMAKE_TARGET  = PaymentServer
DESTDIR       = 
TARGET        = PaymentServer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: PaymentServer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile PaymentServer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile PaymentServer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PaymentServer1.0.0 || $(MKDIR) .tmp/PaymentServer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PaymentServer1.0.0/ && (cd `dirname .tmp/PaymentServer1.0.0` && $(TAR) PaymentServer1.0.0.tar PaymentServer1.0.0 && $(COMPRESS) PaymentServer1.0.0.tar) && $(MOVE) `dirname .tmp/PaymentServer1.0.0`/PaymentServer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PaymentServer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp threadpool.h \
		thread.h \
		data/authorise.h \
		data/param.h \
		paymentserver.h \
		paypal.h \
		data/response.h \
		rqueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

threadpool.o: threadpool.cpp threadpool.h \
		thread.h \
		data/authorise.h \
		data/param.h \
		workerthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o threadpool.o threadpool.cpp

thread.o: thread.cpp thread.h \
		data/authorise.h \
		data/param.h \
		paypal.h \
		data/response.h \
		rqueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread.o thread.cpp

paymentserver.o: paymentserver.cpp workerthread.h \
		paymentserver.h \
		threadpool.h \
		thread.h \
		data/authorise.h \
		data/param.h \
		rqueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paymentserver.o paymentserver.cpp

paypal.o: paypal.cpp paypal.h \
		data/response.h \
		data/authorise.h \
		data/param.h \
		md5/md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paypal.o paypal.cpp

md5.o: md5/md5.c md5/conf.h \
		md5/md5.h \
		md5/md5_loc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md5.o md5/md5.c

param.o: data/param.cpp data/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o param.o data/param.cpp

authorise.o: data/authorise.cpp data/authorise.h \
		data/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o authorise.o data/authorise.cpp

response.o: data/response.cpp data/response.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o response.o data/response.cpp

rqueue.o: rqueue.cpp rqueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rqueue.o rqueue.cpp

workerthread.o: workerthread.cpp workerthread.h \
		thread.h \
		data/authorise.h \
		data/param.h \
		rqueue.h \
		threadpool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workerthread.o workerthread.cpp

redparam.o: data/redparam.cpp data/redparam.h \
		data/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o redparam.o data/redparam.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

